spring.application.name=aurora-mall
spring.profiles.active=${APP_PROFILE:local}

server.port=${APP_PORT:28089}
spring.datasource.name=aurora-mall-datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${APP_DB_URL:jdbc:mysql://localhost:3306/aurora_mall_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true}
spring.datasource.username=${APP_DB_USERNAME:}
spring.datasource.password=${APP_DB_PASSWORD:}
spring.datasource.hikari.minimum-idle=${APP_DB_POOL_MIN_IDLE:5}
spring.datasource.hikari.maximum-pool-size=${APP_DB_POOL_MAX_SIZE:15}
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.pool-name=auroraMallHikariPool
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1
mybatis.mapper-locations=classpath:mapper/*Mapper.xml
