# Generated by Django 3.2.8 on 2023-03-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='角色名称')),
                ('abbreviation', models.CharField(blank=True, max_length=32, null=True, verbose_name='缩写')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('password', models.CharField(default='123', max_length=50, verbose_name='密码')),
                ('email', models.CharField(default='1@qq.com', max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(default='15953654789', max_length=11, verbose_name='手机')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('description', models.TextField(verbose_name='个人描述')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role', verbose_name='角色')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
