# Generated by Django 3.2.8 on 2023-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=100, verbose_name='图片名')),
                ('answer', models.CharField(default='', max_length=100, verbose_name='结果')),
                ('status', models.CharField(default='', max_length=100, verbose_name='状态')),
                ('owner', models.CharField(default='', max_length=100, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
